kind: "DatadogAgent"
apiVersion: "datadoghq.com/v2alpha1"
metadata:
  name: "datadog"
spec:
  global:
    clusterName: "netlix-dev"
    site: "datadoghq.eu"
    credentials:
      apiSecret:
        secretName: "datadog-secret"
        keyName: "api-key"
  features:
    clusterChecks:
      enabled: true
    orchestratorExplorer:
      enabled: true
    apm:
      instrumentation:
        enabled: true
        targets:
          - name: "default-target"
            ddTraceVersions:
              java: "1"
              python: "4"
              js: "5"
              php: "1"
              dotnet: "3"
              ruby: "2"
            ddTraceConfigs:
              - name: "DD_RUM_ENABLED"
                value: "true"
              - name: "DD_RUM_APPLICATION_ID"
                value: "c4e21dc1-c7c9-4d37-ae40-ddd23c33c64a"
              - name: "DD_RUM_CLIENT_TOKEN"
                value: "pub9bfc33c87adbaf3c3a50f7be453810b6"
              - name: "DD_RUM_REMOTE_CONFIGURATION_ID"
                value: "e5d1139e-2c4c-48b1-b7e4-078d43a4d4f0"
              - name: "DD_RUM_SITE"
                value: "datadoghq.eu"
    logCollection:
      enabled: true
      containerCollectAll: true
    autoscaling:
      workload:
        enabled: true
    eventCollection:
      unbundleEvents: true
