apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway
  namespace: consul
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: consul
spec:
  selector:
    app: gateway
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: consul
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      serviceAccountName: gateway
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        fsGroup: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: gateway
          image: netlix-gateway
          ports:
            - containerPort: 8080
          env:
            - name: CATALOG_URL
              value: "http://catalog.consul.svc.cluster.local:8080"
            - name: AUTH_URL
              value: "http://auth.consul.svc.cluster.local:8080"
            - name: ORDERS_URL
              value: "http://orders.consul.svc.cluster.local:8080"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          resources:
            requests: { cpu: 150m, memory: 128Mi }
            limits:   { cpu: 1500m, memory: 512Mi }
          readinessProbe:
            httpGet: { path: /ready, port: 8080 }
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /health, port: 8080 }
            periodSeconds: 30
---
# Public ALB ingress for the shop. ExternalDNS will create the Route53 A record.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shop
  namespace: consul
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:eu-central-1:173003892479:certificate/72a5bfed-9f0f-4cb5-a661-2a275ee05a6a"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443},{"HTTP":80}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/success-codes: '200'
    external-dns.alpha.kubernetes.io/hostname: app.dev.netlix.dev
spec:
  ingressClassName: alb
  rules:
    - host: app.dev.netlix.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 8080
