# VSO mints a Vault PKI cert per shop service into a kubernetes.io/tls Secret.
# TTL = 1h, refreshAfter = 40m (67% of lifetime). Rolling restart on rotation.
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultPKISecret
metadata:
  name: catalog-tls
  namespace: consul
spec:
  vaultAuthRef: default
  namespace: admin
  mount: pki_int
  role: netlix-app
  commonName: catalog.consul.svc.cluster.local
  altNames:
    - catalog.consul.svc.cluster.local
  ttl: "1h"
  refreshAfter: "40m"
  revoke: true
  destination:
    name: catalog-tls
    create: true
    type: kubernetes.io/tls
  rolloutRestartTargets:
    - kind: Deployment
      name: catalog
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultPKISecret
metadata:
  name: auth-tls
  namespace: consul
spec:
  vaultAuthRef: default
  namespace: admin
  mount: pki_int
  role: netlix-app
  commonName: auth.consul.svc.cluster.local
  altNames:
    - auth.consul.svc.cluster.local
  ttl: "1h"
  refreshAfter: "40m"
  revoke: true
  destination:
    name: auth-tls
    create: true
    type: kubernetes.io/tls
  rolloutRestartTargets:
    - kind: Deployment
      name: auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultPKISecret
metadata:
  name: orders-tls
  namespace: consul
spec:
  vaultAuthRef: default
  namespace: admin
  mount: pki_int
  role: netlix-app
  commonName: orders.consul.svc.cluster.local
  altNames:
    - orders.consul.svc.cluster.local
  ttl: "1h"
  refreshAfter: "40m"
  revoke: true
  destination:
    name: orders-tls
    create: true
    type: kubernetes.io/tls
  rolloutRestartTargets:
    - kind: Deployment
      name: orders
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultPKISecret
metadata:
  name: gateway-tls
  namespace: consul
spec:
  vaultAuthRef: default
  namespace: admin
  mount: pki_int
  role: netlix-app
  commonName: gateway.consul.svc.cluster.local
  altNames:
    - gateway.consul.svc.cluster.local
  ttl: "1h"
  refreshAfter: "40m"
  revoke: true
  destination:
    name: gateway-tls
    create: true
    type: kubernetes.io/tls
  rolloutRestartTargets:
    - kind: Deployment
      name: gateway
