apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: netlix-web
  newName: ghcr.io/timkrebs/netlix-platform/web
  newTag: 76f136d53051ac8bad48dd953a310f020e9898a0

patches:
- path: patch-web-ingress.yaml
  target:
    kind: Ingress
    name: web
- path: patch-web-env.yaml
  target:
    kind: Deployment
    name: web
- path: patch-api-env.yaml
  target:
    kind: Deployment
    name: api
- path: patch-vault-auth.yaml
  target:
    kind: VaultAuth
    name: default
- path: patch-vault-pki.yaml
  target:
    kind: VaultPKISecret
    name: web-tls
