apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: consul
spec:
  template:
    metadata:
      labels:
        tags.datadoghq.com/env: "dev"
    spec:
      containers:
        - name: api
          env:
            - name: DD_ENV
              value: "dev"
