apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: consul
spec:
  template:
    spec:
      containers:
        - name: web
          env:
            - name: ENVIRONMENT
              value: "dev"
