apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: netlix-web
  newName: ghcr.io/timkrebs/netlix-platform/web
  newTag: dev-4c23abedc87bdf62047aee954a074a3b06a798a3

patches:
- path: patch-web-ingress.yaml
  target:
    kind: Ingress
    name: web
- path: patch-web-env.yaml
  target:
    kind: Deployment
    name: web
- path: patch-api-env.yaml
  target:
    kind: Deployment
    name: api
- path: patch-vault-auth.yaml
  target:
    kind: VaultAuth
    name: default
- path: patch-vault-pki.yaml
  target:
    kind: VaultPKISecret
    name: web-tls
