apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: consul
spec:
  template:
    spec:
      containers:
        - name: api
          env:
            - name: ENVIRONMENT
              value: "dev"
            - name: VERSION
              value: "latest"
