apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../web/deployment.yaml
  - ../web/pdb.yaml
  - ../web/hpa.yaml
  - ../api/deployment.yaml
  - ../api/pdb.yaml
  - ../api/hpa.yaml
  # Consul service mesh — uncomment when Consul is deployed
  # - ../mesh/proxy-defaults.yaml
  # - ../mesh/intentions.yaml
  - resource-quota.yaml
  - vault-pki-secret.yaml
