apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultPKISecret
metadata:
  name: web-tls
  namespace: consul
spec:
  vaultAuthRef: default
  namespace: admin/dev
  mount: pki_int
  role: netlix-app
  commonName: web.dev.netlix.dev
  altNames:
    - web.consul.svc.cluster.local
  ttl: 72h
  expiryOffset: 1h
  destination:
    name: web-tls
    create: true
