apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: default
  namespace: consul
spec:
  method: kubernetes
  mount: kubernetes
  vaultConnectionRef: vault-secrets-operator-system/default
  kubernetes:
    role: netlix-vso
    serviceAccount: vault-secrets-operator-controller-manager
    tokenExpirationSeconds: 600
