aws_region          = "eu-central-1"
role_arn            = "arn:aws:iam::role/tfc-netlix-dev"
hcp_project_id      = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
vault_cluster_id    = "netlix-vault"
vpc_cidr            = "10.0.0.0/16"
azs                 = ["eu-central-1a", "eu-central-1b", "eu-central-1c"]
cluster_name        = "netlix-dev"
cluster_version     = "1.31"
node_instance_types = ["m6i.large"]
node_desired_size   = 3
node_min_size       = 2
node_max_size       = 5
db_instance_class   = "db.t4g.medium"
db_name             = "netlix"
db_engine_version   = "16.4"
github_org          = "timkrebs"
environment         = "dev"
project             = "netlix"
